apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  ports:
  - name: 5432-5432
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
  type: ClusterIP
