apiVersion: v1
kind: Service
metadata:
  name: {{ include "bankapp.fullname" . }}
  labels:
    app: thebank
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: thebank
