apiVersion: apps/v1
kind: Deployment
metadata:
  name: thebank
  labels:
    app: thebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thebank
  template:
    metadata:
      labels:
        app: thebank
    spec:
      containers:
      - name: thebank
        image: jullmg/thebankapp:latest
        